### ISSUE TITLE
Is it possible to disable the "typing right away" behavior?

### ISSUE THREAD

**Issue by Diullei** [ziontee113/SelectEase#2]
Hei very nice plugin! Thank you for creating and sharing it with the community! :)

Would it be possible to have a `flag` in the configuration to disable the "typing right away" behavior in case I just want to use the navigation feature? 

Case you don't have the intention to add this `flag`, do you mind pointing me to where I would need to change it in order to disable it?

**Comment by ziontee113** [comment]
Hi @Diullei , this has been implemented at 63c0d481204d5ff61554c695d21d2979b82dc277.

You use this behavior, you can add the option `visual_mode = true` into your mappings.

**Comment by Diullei** [comment]
@ziontee113  Ok, thanks! :)
