### ISSUE TITLE
Is it possible to add a "exchange text" feature?

### ISSUE THREAD

**Issue by bommbo** [ziontee113/SelectEase#3]
Thank you this powerful plugin. Did you plan to add some "exchange text" feature like iswap.nvim or nvim-treesitter-textobjects ?

**Comment by ziontee113** [comment]
Hi @bommbo , there is currently no plan to introduce the "exchange text" or "swap" feature into SelectEase. However, I'm interested to hear your need / use case for the feature within the context of SelectEase, maybe you'll change my mind.

In the meantime, maybe you can check out another plugin that can do that https://github.com/ziontee113/syntax-tree-surfer

**Comment by bommbo** [comment]
This is a vscode extension example , https://github.com/DnailZ/oomotion_vscode . I like the feature about" select & move" and "exchange text". Hope I can change your mind.

**Comment by ziontee113** [comment]
This feature would be cool to have. I'll take a look at it and assess when and how to implement it. Thank you for opening the issue.

**Comment by ziontee113** [comment]
Hi @bommbo , I've tried to implement this feature. Please update your plugins to receive the changes.
I'd love to hear your feedback about the implementation and about this issue :+1:

**Comment by bommbo** [comment]
sorry. It's not working for me.The cursor just jump next/previous node with another shortcuts. It has same behavior.

**Comment by ziontee113** [comment]
@bommbo have you tried these mappings? To swap nodes, we use `swap_nodes()` instead of `select_node()`.

```lua

        -- Swap Nodes
        vim.keymap.set({ "n", "s", "i" }, "<C-A-S-k>", function()
            select_ease.swap_nodes({
                queries = queries,
                direction = "previous",
                vertical_drill_jump = true,

                -- swap_in_place option. Default behavior is cursor will jump to target after the swap
                -- jump_to_target_after_swap = false --> this will keep cursor in place after the swap
            })
        end, {})
        vim.keymap.set({ "n", "s", "i" }, "<C-A-S-j>", function()
            select_ease.swap_nodes({
                queries = queries,
                direction = "next",
                vertical_drill_jump = true,
            })
        end, {})
        vim.keymap.set({ "n", "s", "i" }, "<C-A-S-h>", function()
            select_ease.swap_nodes({
                queries = queries,
                direction = "previous",
                current_line_only = true,
            })
        end, {})
        vim.keymap.set({ "n", "s", "i" }, "<C-A-S-l>", function()
            select_ease.swap_nodes({
                queries = queries,
                direction = "next",
                current_line_only = true,
            })
        end, {})
        vim.keymap.set({ "n", "s", "i" }, "<C-A-S-p>", function()
            select_ease.swap_nodes({ queries = queries, direction = "previous" })
        end, {})
        vim.keymap.set({ "n", "s", "i" }, "<C-A-S-n>", function()
            select_ease.swap_nodes({ queries = queries, direction = "next" })
        end, {})
```

**Comment by bommbo** [comment]
[Screencast from 2023-02-20 04-22-13.webm](https://user-images.githubusercontent.com/61496351/219973338-9c02ccdd-7e10-4935-ba98-b0189cb456bb.webm)

**Comment by ziontee113** [comment]
@bommbo this might have to do with your terminal emulator :thinking: 

Can you map `<C-A-S-j>`, `<C-A-S-k>` to anything else to confirm that it works? Like:

```lua
vim.keymap.set({ "n", "s", "i" }, "<C-A-S-k>", function()
    print("<C-A-S-k> is pressed")
end, {})
vim.keymap.set({ "n", "s", "i" }, "<C-A-S-j>", function()
    print("<C-A-S-j> is pressed")
end, {})
```

**Comment by bommbo** [comment]
I don't know it's the terminal emulator's problem or not . But It's working for another shortcut.  Here is a discuss about "swap words" e.g. https://www.reddit.com/r/vim/comments/p1ehei/how_can_i_swap_words/ , I think your plugin is the most elegant way . But It can't be used without Treesitter. Thank you this power plugin.

**Comment by ziontee113** [comment]
I'm glad that `swap_nodes` is working for you. I'll close this issue for now. Feel free to reopen it if you run into `swap_nodes` issues.
