### ISSUE TITLE
Fallback for node didn't found

### ISSUE THREAD

**Issue by ofirgall** [ziontee113/SelectEase#7]
Hey, I would like to have "select next" as a fallback when "Select Down" didn't find any node to jump to.

I think the most robust way to implement this feature is to add `fallback` function callback when calling `select_node` function.

**Comment by ziontee113** [comment]
Hi @ofirgall , I've implemented this feature with 64dca929baf3cd873348d7a09abf35ae344b0342. Please update the plugin to receive the changes. Please feel free to send me feedback regarding this issue :+1:

**Comment by ofirgall** [comment]
Hey @ziontee113, thanks for the quick reply, your implementation didn't work, it missed `elseif` for `if smallest_node`.

```lua
    if smallest_node then
        ................
        if #candidates > 0 then
            local left_most_node = find_left_most_node(candidates)
            select_node(left_most_node, opts)
        elseif opts.fallback then
            opts.fallback()
        end
    elseif opts.fallback then -- <---------- this elseif
        opts.fallback()
    end
```

**Comment by ziontee113** [comment]
Hi @ofirgall , I've pushed a few more commits since then. It works ok on my end. Please update your plugin and see if the latest commit fixes your problem.

**Comment by ofirgall** [comment]
It works now! Thanks
